version: '3.8'

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      zookeeper1:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025   # web UI port - http://localhost:8025. To view specific mail: <Mailpit URL>/view/<ID>.(html|txt)
                    # We can substitute ID with "latest", e.g. http://localhost:8025/view/latest.html
      - 1025:1025   # SMTP port
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /notification-service-submodule/data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1